apiVersion: influxdata.com/v1alpha1
kind: Restore
metadata:
  name: influxdb-restore
spec:
  database: "test"
  restoreTo: "test_bak"         # optional. defaults to {database}_restore
  backupId: "20181113084224"
  storage:
    s3:
      aws_key_id:
        valueFrom:
          secretKeyRef:
            name: influxdb-backup
            key: awsAccessKeyId
      aws_secret_key:
        valueFrom:
          secretKeyRef:
            name: influxdb-backup
            key: awsSecretAccessKey
      bucket: dbarnes-influx-backups
      folder: backup
      region: us-west-2
