apiVersion: influxdata.com/v1alpha1
kind: Restore
metadata:
  name: influxdb-restore
spec:
  database: "testdb"
<<<<<<< HEAD
  restoreTo: "testdb"         # optional. defaults to {database}
  backupId: "20181114181703"
=======
  restoreTo: "testdb2"
  backupId: "20181116184626"
  podname: "influxdb-0"
  containername: "influxdb"
  #rp:
>>>>>>> commands-flags
  storage:
    s3:
      aws_key_id:
        valueFrom:
          secretKeyRef:
            name: influxdb-backup
            key: awsAccessKeyId
      aws_secret_key:
        valueFrom:
          secretKeyRef:
            name: influxdb-backup
            key: awsSecretAccessKey
      bucket: influxdb-backup-restore 
      folder: backup
      region: us-west-2
