kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: standard-resize
provisioner: docker.io/hostpath
reclaimPolicy: Retain
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: influxdb-data-pvc
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard-resize