apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: no-provisioner
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-data-pv-nfs
  namespace: influxdata
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: no-provisioner
  nfs:
    path: /data
    server: nfs.openshift.example.com 
